#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    printf("%c]0;%s%c", '\033', "Number Guessing Game", '\007');
    int high_score = 1000, level = 1, no_of_guesses = 0, guessed_number;
    char choices;

    // Initialize random number generator
    srand(time(0));

menu: // game menu.
{
    system("cls");
    no_of_guesses=0;
    printf("\n\t\t\t\t\t\tNumber Guessing Game!\n\n"); // Title
    // menu
    printf("##############################\n\n1.start \t2.Level's \n\n3.High Score = %d \t4.Help \n\n**Press 0 for exit this Game**\n\n#############################\n", high_score);
    printf("\nEnter Your Choice :");
    scanf(" %c",&choices);
    // choices = getchar();
    // Clear input buffer
    while (getchar() != '\n');

    if (choices == '1')
    {
        goto start;
    }
    else if (choices == '2')
    {
        goto level_game;
    }
    else if (choices == '3')
    {
        printf("\nNo Choices are Available!\nPlease Try again!!\n\n");
        system("pause");
        goto menu;
    }
    else if (choices == '4')
    {
        goto helps;
    }
    else if (choices == '0')
    {
        goto end;
    }
    else
    {
        goto menu;
    }
}
level_game: // change levels of this game.
{
    system("cls");
    printf("\n\t\t\t\t\t\tNumber Guessing Game!\n\n"); // Title

    // Default settings.
    printf("Default Level is Easy !!\n");
    // Prompt user to change settings
    printf("Levels\n\n 1.Easy \t 2.Normal \t 3.Hard\n");
    printf("\nEnter New Level :");
    scanf("%d", &level);
    if (level < 1 || level > 3)
    {
        level = 1; // Default to Easy if input is invalid
        goto menu;
    }
    printf("Setting Updated !!\n");
    system("pause");
    goto menu;
}
helps: // shows help of this game.
{
    system("cls");
    printf("\n\t\t\t\t\t\tNumber Guessing Game!\n\n"); // Title
    printf("HELP\n");
    printf("1. Start: Begin a new game.\n");
    printf("2. Levels: Change the difficulty level.\n");
    printf("3. High Score: View the high score.\n");
    printf("4. Help: View this help message.\n");
    printf("0. Exit: Quit the game.\n");
    printf("\nHOW TO PLAY:\n");
    printf("1. Select a level to begin the game:\n");
    printf("   - Easy: Guess a number between 1 and 100.\n");
    printf("   - Normal: Guess a number between 1 and 500.\n");
    printf("   - Hard: Guess a number between 1 and 1000.\n");
    printf("2. Try to guess the number generated by the computer.\n");
    printf("3. The game will prompt if your guess is too high or too low.\n");
    printf("4. Keep guessing until you find the correct number.\n");
    printf("5. Your score is based on the number of guesses you take.\n");
    printf("\nTIPS:\n");
    printf("1. Try to use the hints given to narrow down your guesses.\n");
    printf("2. The fewer guesses you make, the higher your score will be.\n");
    printf("\nPress Enter to return to the menu...");
    getchar();
    goto menu;
}
start: // start the game.
{
    system("cls");
    printf("\n\t\t\t\t\t\tNumber Guessing Game!\n\n"); // Title
    if (level == 1)                                    // Easy level.
    {
        printf("::Easy::\n\n");
        // Generate random number between 1 and 100
        int randomNumber = (rand() % 100) + 1;

        // Print the random number
        do
        {
            printf("\nGuess The number:");
            scanf("%d", &guessed_number);
            if (guessed_number > randomNumber)
            {
                printf("\nLower Number Please!!\n");
            }
            else if (guessed_number < randomNumber)
            {
                printf("\nHigher Number please!!\n");
            }
            else
            {
                printf("\nCongrats!!\n");
            }
            no_of_guesses++;
        } while (guessed_number != randomNumber);
        printf("\nYou Guessed The number in %d guesses !!\n", no_of_guesses);
        if (no_of_guesses < high_score)
        {
            high_score = no_of_guesses;
            printf("\n\nCongratulations!!\nYou create new High Score : %d !!\n\n", high_score);
        }

        system("pause");
        goto menu;
    }
    else if (level == 2) // Normal level.
    {
        printf("::Normal::\n\n");
        // Generate random number between 1 and 500
        int randomNumber = (rand() % 500) + 1;

        // Print the random number
        do
        {
            printf("\nGuess The number:");
            scanf("%d", &guessed_number);
            if (guessed_number > randomNumber)
            {
                printf("\nLower Number Please!!\n");
            }
            else if (guessed_number < randomNumber)
            {
                printf("\nHigher Number please!!\n");
            }
            else
            {
                printf("\nCongrats!!\n");
            }
            no_of_guesses++;
        } while (guessed_number != randomNumber);
        printf("\nYou Guessed The number in %d guesses !!\n", no_of_guesses);
        if (no_of_guesses < high_score)
        {
            high_score = no_of_guesses;
            printf("\n\nCongratulations!!\nYou create new High Score : %d !!\n\n", high_score);
        }
        system("pause");
        goto menu;
    }
    else if (level == 3) // Hard Level.
    {
        printf("::Hard::\n\n");
        // Generate random number between 1 and 1000
        int randomNumber = (rand() % 1000) + 1;

        // Print the random number
        do
        {
            printf("\nGuess The number:");
            scanf("%d", &guessed_number);
            if (guessed_number > randomNumber)
            {
                printf("\nLower Number Please!!\n");
            }
            else if (guessed_number < randomNumber)
            {
                printf("\nHigher Number please!!\n");
            }
            else
            {
                printf("\nCongrats!!\n");
            }
            no_of_guesses++;
        } while (guessed_number != randomNumber);
        printf("\nYou Guessed The number in %d guesses !!\n", no_of_guesses);
        if (no_of_guesses < high_score)
        {
            high_score = no_of_guesses;
            printf("\n\nCongratulations!!\nYou create new High Score : %d !!\n\n", high_score);
        }
        system("pause");
        goto menu;
    }
}
end: // to exit the game.
{
    exit(0);
}

    return 0;
}